export const ADD_DEVICE = 'ADD_DEVICE';
export const REMOVE_DEVICE = 'REMOVE_DEVICE';
export const RETRIEVE_DEVICES = 'RETRIEVE_DEVICES';
export const SELECT_DEVICE = 'SELECT_DEVICE';

export const ADD_ANIMATION = 'ADD_ANIMATION';
export const REMOVE_ANIMATION = 'REMOVE_ANIMATION';
